server:
  port: 8081
spring:
  application:
    name: "ms-payment"
  devtools:
    add-properties: false
  flyway:
    url: jdbc:postgresql://localhost:5432/payment_db
    user: postgres
    password: 1234
    baseline-on-migrate: true
    enabled: true
  r2dbc:
    url: "r2dbc:postgresql://localhost:5432/payment_db"
    username: "postgres"
    password: 1234
  profiles:
    include: null
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
  health:
    circuitbreakers:
      enabled: false
cors:
  allowed-origins: "http://localhost:4200,http://localhost:8080"
adapter:
  restconsumer:
    timeout: 5000
    url: "http://localhost:8080"
resilience4j:
  circuitbreaker:
    instances:
      commerceManagement:
        registerHealthIndicator: false
        failureRateThreshold: 50
        slowCallRateThreshold: 50
        slowCallDurationThreshold: "2s"
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        minimumNumberOfCalls: 10
        waitDurationInOpenState: "10s"
